defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: simple_bbs_<%= Rails.env %>
  username: postgres
  password:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
