defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gyo
  password:

development:
  <<: *defaults
  database: siimple_bbs_development

test:
  <<: *defaults
  database: siimple_bbs_test

production:
  <<: *defaults
  database: siimple_bbs_production
